.MODEL SMALL
.STACK 100H

.DATA
    MSG1 DB 'ENTER STRING: $'
    MSG2 DB 0DH,0AH,'ENCRYPTED: $'
    MSG3 DB 0DH,0AH,'DECRYPTED: $'
    
    STR DB 50 DUP('$')
    LEN DW 0
    
    ; SIMPLE ENCRYPTION TABLE - SHIFTS EACH LETTER
    ENC_TABLE DB 'NOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLM'
    DB '!@#$%^&*()`~-_=+[{]}\|;:''",<.>/?0123456789 ', 0DH
    
    ; DECRYPTION TABLE - REVERSE OF ENCRYPTION
    DEC_TABLE DB 'ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ'
    DB '!@#$%^&*()`~-_=+[{]}\|;:''",<.>/?0123456789 ', 0DH

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ; DISPLAY PROMPT
    LEA DX, MSG1
    MOV AH, 09H
    INT 21H
    
    ; READ STRING
    LEA SI, STR
    XOR CX, CX
    
INPUT:
    MOV AH, 01H
    INT 21H
    CMP AL, 0DH
    JE DONE_INPUT
    MOV [SI], AL
    INC SI
    INC CX
    JMP INPUT
    
DONE_INPUT:
    MOV LEN, CX
    
    ; ENCRYPT USING XLAT
    LEA SI, STR
    MOV CX, LEN
    LEA BX, ENC_TABLE
    
ENCRYPT:
    MOV AL, [SI]
    SUB AL, 65        ; ADJUST TO TABLE INDEX (A=0)
    XLAT              ; AL = ENC_TABLE[AL]
    MOV [SI], AL
    INC SI
    LOOP ENCRYPT
    
    ; DISPLAY ENCRYPTED
    LEA DX, MSG2
    MOV AH, 09H
    INT 21H
    LEA DX, STR
    MOV AH, 09H
    INT 21H
    
    ; DECRYPT USING XLAT
    LEA SI, STR
    MOV CX, LEN
    LEA BX, DEC_TABLE
    
DECRYPT:
    MOV AL, [SI]
    SUB AL, 65        ; ADJUST TO TABLE INDEX
    XLAT              ; AL = DEC_TABLE[AL]
    MOV [SI], AL
    INC SI
    LOOP DECRYPT
    
    ; DISPLAY DECRYPTED
    LEA DX, MSG3
    MOV AH, 09H
    INT 21H
    LEA DX, STR
    MOV AH, 09H
    INT 21H
    
    ; EXIT
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN
